name: build and push to docker

on: [push]

jobs:
  build-push:
   runs-on: ubuntu-latest

   steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: set up buildx
       uses: docker/setup-buildx-action@v3

     - name: log in to docker
       uses: docker/login-action@v3
       with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: build and push docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: mayurv54/demo:dockerdemo.v1
